名字: Python Package using Conda

在: [push]

工作:
构建-linux:
连续运行: ubuntu-latest
战略:
最大并行度: 5

步伐:
    - 使用: actions/checkout@v4
    - 名字: Set up Python 3.10
使用: actions/setup-python@v3
随着:
python版本: '3.10'
    - 名字: Add conda to system path
奔跑: |
# $CONDA是指向miniconda目录根目录的环境变量
echo $CONDA/bin >> $GITHUB_PATH
    - 名字: Install dependencies
奔跑: |
conda环境更新-文件environment.yml -名称库
    - 名字: Lint with flake8
奔跑: |
康达安装薄板8
#如果有Python语法错误或未定义的名称，停止构建
flake8。-计数-选择=E9，F63，F7，F82 -显示-来源-统计
# exit-zero将所有错误视为警告。GitHub编辑器有127个字符宽
flake8。-计数-退出-零-最大复杂性=10 -最大行长度=127 -统计
    - 名字: 用pytest测试
奔跑: |
康达安装pytest
pytest
